apiVersion: v1
kind: ConfigMap
metadata:
  name: storefront-config
data:
  NEXT_PUBLIC_BASE_URL: "https://store.your-domain.com"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
spec:
  replicas: 3