apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medusajs-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tural-musab/medusajs-k8s-cicd
    targetRevision: main
    path: k8s-manifests
    directory:
      include: '*-staging.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: medusajs-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespaceIfNotPresent=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
