# MedusaJS ConfigMap
# Bu dosya environment variables'ları tanımlar
# Railway'deki "Environment Variables" sekmesinin K8s karşılığı

apiVersion: v1
kind: ConfigMap
metadata:
  name: medusa-config
data:
  # Database bağlantısı
  DATABASE_URL: "postgresql://medusauser:medusapassword@postgres-service:5432/medusadb"
  
  # Redis bağlantısı  
  REDIS_URL: "redis://redis-service:6379"
  
  # MeiliSearch bağlantısı
  MEILISEARCH_HOST: "http://meilisearch-service:7700"
  MEILISEARCH_API_KEY: "your-master-key-change-this"
  
  # MedusaJS ayarları
  NODE_ENV: "development"
  NPM_CONFIG_PRODUCTION: "false"
  STORE_CORS: "http://localhost:8000,http://localhost:3000"
  ADMIN_CORS: "http://localhost:7001,http://localhost:9000"
  
  # JWT Secret (Production'da gerçek secret kullan)
  JWT_SECRET: "supersecret"
  COOKIE_SECRET: "supersecret"
