apiVersion: v1
kind: ConfigMap
metadata:
  name: medusa-config
data:
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/medusajs"
  REDIS_URL: "redis://redis-service:6379"
  # JWT_SECRET and COOKIE_SECRET moved to secrets.yaml
  MEDUSA_BACKEND_URL: "http://medusa-backend-service:9000"