apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  labels:
    app: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
      - name: meilisearch
        image: getmeili/meilisearch:v1.5
        ports:
        - containerPort: 7700
        env:
        - name: MEILI_ENV
          value: "development"
        - name: MEILI_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: medusa-secrets
              key: meilisearch-master-key
        volumeMounts:
        - name: meilisearch-storage
          mountPath: /meili_data
      volumes:
      - name: meilisearch-storage
        persistentVolumeClaim:
          claimName: meilisearch-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch-service
spec:
  selector:
    app: meilisearch
  ports:
  - protocol: TCP
    port: 7700
    targetPort: 7700
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi