apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medusajs-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - staging-api.your-domain.com
    - staging-store.your-domain.com
    secretName: staging-tls-secret
  rules:
  - host: staging-store.your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: storefront-service
            port:
              number: 3000
  - host: staging-api.your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: medusa-backend-service
            port:
              number: 9000