apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: staging-

commonLabels:
  environment: staging
  
patchesStrategicMerge:
- replica-patch.yaml
- config-patch.yaml
- image-patch.yaml
- storefront-patch.yaml
- ingress-patch.yaml